VitrineVirtual.WEB/Controllers/CUAUsuariosController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using NLog;
using NLog.Fluent;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using System.Web.UI;
using VitrineVirtual.Data;
using VitrineVirtual.Model;

namespace VitrineVirtual.WEB.Controllers
{
    //[Authorize(Roles = "Administrator,Logista,Revendedor")]
    public class CUAUsuariosController : Controller
    {
        private VitrineVirtualDBContext db = new VitrineVirtualDBContext();
        Logger log = LogManager.GetCurrentClassLogger();
        Page page = new Page();


        // GET: CUA_Usuarios
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        /// <summary>
        /// Método resposável de filtrar por empresas.
        /// </summary>
        /// <param name="pesquisa"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FiltrarPorNome(string pesquisa)
        {
            try
            {
                var produtoSelecionado = db.Usuarios.Where(a => a.Login_Usuario.Contains(pesquisa)).OrderBy(a => a.Login_Usuario).ToList();
                return View(produtoSelecionado);
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return RedirectToAction("Index");
            }

        }

        /// <summary>
        /// Método de retorno dos dados pelos correios
        /// </summary>
        /// <param name="cnpj"></param>
        /// <param name="cep"></param>
        /// <returns></returns>
        public ActionResult retornaDadosPorCNPJ(string cnpj)
        {
            try
            {
                CUA_Usuarios usuarios = new CUA_Usuarios();
                var resultCNPJ = EmpresaDados(cnpj);


                if (cnpj != null)
                {
                    usuarios.Bairro = resultCNPJ.bairro;
                    usuarios.Cep = resultCNPJ.cep.Replace(".", "").Replace("-", "").Replace("/", "");
                    usuarios.Municipio = resultCNPJ.municipio;
                    usuarios.Complemento = resultCNPJ.complemento;
                    usuarios.UF = resultCNPJ.uf;
                    usuarios.Endereco = resultCNPJ.logradouro;
                    usuarios.Numero_Endereco = resultCNPJ.numero;
                    usuarios.Situacao_Cadastral = resultCNPJ.situacao;
                    usuarios.Nome_Completo = resultCNPJ.nome;
                    usuarios.Telefone = resultCNPJ.telefone.Replace("(", "").Replace(")", "").Replace("-", "");
                    usuarios.CNPJ = resultCNPJ.cnpj.Replace(".", "").Replace("-", "").Replace("/", "");

                    return View("Create", usuarios);
                }
                
                else
                {
                    return View(usuarios);
                }
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return null;
            }


        }

        public ActionResult PesquisaUsuario(string email)
        {
            var cadastraUsuario = db.Usuarios.Where(x => x.Email == email).ToList();
            CUA_Usuarios usuarios = new CUA_Usuarios();
            usuarios.Email = cadastraUsuario[0].Email;
            usuarios.Login_Usuario = cadastraUsuario[0].Login_Usuario;
            usuarios.id = cadastraUsuario[0].id;

            return View("Create", usuarios);
        }

        // GET: CUA_Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUA_Usuarios cUA_Usuarios = db.Usuarios.Find(id);
            if (cUA_Usuarios == null)
            {
                return HttpNotFound();
            }
            return View(cUA_Usuarios);
        }

        // GET: CUA_Usuarios/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return View();
            }
        }

        // POST: CUA_Usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome_Completo,Login_Usuario,Email,Telefone,Departamento,Cargo,Data_Nascimento,Cpf,Rg,Cep,Endereco,Numero_Endereco,Complemento,Bairro,Municipio,Status_Usuario,Data_Criacao,Data_Ultimo_Logon,CNPJ,Tipo_Usuario")] CUA_Usuarios CUA_Usuarios)
        {
            try
            {
                CUA_Usuarios.Data_Criacao = DateTime.Now;
                CUA_Usuarios.Data_Ultimo_Logon = DateTime.Now;

                if (ModelState.IsValid)
                {
                    db.Usuarios.Add(CUA_Usuarios);
                    db.SaveChanges();
                    ScriptManager.RegisterStartupScript(page, page.GetType(), "showPopUpConfirm", "showPopUpConfirm('Alerta!','Deseja realmente cadastrar esse usuário?','warning');", true);

                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return View();
            }

            return View(CUA_Usuarios);
        }

        // GET: CUA_Usuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUA_Usuarios cUA_Usuarios = db.Usuarios.Find(id);
            if (cUA_Usuarios == null)
            {
                return HttpNotFound();
            }
            return View(cUA_Usuarios);
        }

        // POST: CUA_Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nome_Completo,Login_Usuario,Email,Telefone,Departamento,Cargo,Data_Nascimento,Cpf,Rg,Cep,Endereco,Numero_Endereco,Complemento,Bairro,Municipio,Status_Usuario,Data_Criacao,Data_Ultimo_Logon,CNPJ,Tipo_Usuario")] CUA_Usuarios cUA_Usuarios)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(cUA_Usuarios).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(cUA_Usuarios);
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return View();
            }
            
        }

        // GET: CUA_Usuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUA_Usuarios cUA_Usuarios = db.Usuarios.Find(id);
            if (cUA_Usuarios == null)
            {
                return HttpNotFound();
            }
            return View(cUA_Usuarios);
        }

        // POST: CUA_Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                CUA_Usuarios cUA_Usuarios = db.Usuarios.Find(id);
                db.Usuarios.Remove(cUA_Usuarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Método que realiza consulta na API ReceitaWS e retorna os dados da empresa relativa ao CNPJ consultado.
        /// </summary>
        /// <param name="cnpj"></param>
        /// <returns></returns>
        protected ReceitaWS EmpresaDados(string cnpj)
        {
            ReceitaWS jsonResult = new ReceitaWS();
            string responseJson;
            string receitaWS = "https://www.receitaws.com.br/v1/cnpj/";
            string Api_Consulta = receitaWS + cnpj.Replace(".", "").Replace("-", "").Replace("/", "");

            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Clear();

VitrineVirtual.WEB/Views/CUAUsuarios/Create.cshtml
@using VitrineVirtual.Model
@using VitrineVirtual.WEB.Models
@model VitrineVirtual.Model.CUA_Usuarios

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "CUAUsuarios", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div>
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success", @style = "background-color: #3872a2" })
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.Label("Carregar Registro Usuário", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.TextBox("RegistroUsuario", Request.Form["RegistroUsuario"], new { @id = "RegistroUsuario", @class = "form-control", @type = "email" })
            <!-- <input type="text" id="CNPJConsulta" name="CNPJConsulta" class="form-control"> -->
        </div>
        <div>
            @Html.ActionLink("Carregar Registro", "PesquisaUsuario", "CUAUsuarios", new { cnpj = Request.Form["RegistroUsuario"] }, new { @class = "btn btn-success", @style = "background-color: #3872a2" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("CNPJ a Consultar", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.TextBox("CNPJConsulta", Request.Form["CNPJConsulta"], new { @id = "CNPJConsulta", @class = "form-control", @type = "number" })
            <!-- <input type="text" id="CNPJConsulta" name="CNPJConsulta" class="form-control"> -->
        </div>
        <div>
            @Html.ActionLink("Pesquisar Dados", "retornaDadosPorCNPJ", "CUAUsuarios", new { cnpj = Request.Form["CNPJConsulta"] }, new { @class = "btn btn-success", @style = "background-color: #3872a2" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nome_Completo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Nome_Completo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome_Completo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Login_Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Login_Usuario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Login_Usuario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Departamento:</label>
        <div class="col-sm-5">
            @Html.DropDownListFor(x => x.Departamento, new List<SelectListItem>
            {
               new SelectListItem() {Text = "Geral", Value="Geral"},
               new SelectListItem() {Text = "Esporte", Value="Esporte"},
               new SelectListItem() {Text = "Social", Value="Social"},
               new SelectListItem() {Text = "Empresarial", Value="Empresarial"},
               new SelectListItem() {Text = "Infantil", Value="Infantil"},
               new SelectListItem() {Text = "Escolar", Value="Escolar"},
               new SelectListItem() {Text = "Uniformes", Value="Uniformes"}
                },
                  new
                  {
                      @class = "form-control"
                  })
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Função Usuário:</label>
        <div class="col-sm-5">
            @Html.DropDownListFor(x => x.Cargo, new List<SelectListItem>
            {
               new SelectListItem() {Text = "Administrador", Value="Administrador"},
               new SelectListItem() {Text = "Vendedor", Value="Vendedor"},
               new SelectListItem() {Text = "Gerente", Value="Gerente"},
               new SelectListItem() {Text = "Responsável Técnico", Value="Responsável_Tecnico"},
               new SelectListItem() {Text = "Proprietário", Value="Proprietario"},
               new SelectListItem() {Text = "Logistica", Value="Logistica"},
               new SelectListItem() {Text = "Estoque", Value="Estoque"}
            },
            new
            {
                @class = "form-control"
            })
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Função Usuário:</label>
        <div class="col-sm-5">
            @Html.DropDownListFor(x => x.Tipo_Usuario, new List<SelectListItem>
            {
               new SelectListItem() {Text = "Administrador", Value="Administrador"},
               new SelectListItem() {Text = "Logista", Value="Logista"},
               new SelectListItem() {Text = "Revendedor", Value="Revendedor"},
               new SelectListItem() {Text = "Visitante", Value="Visitante"}
            },
            new
            {
                @class = "form-control"
            })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CNPJ, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Rg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Data_Nascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Data_Nascimento, new { htmlAttributes = new { @class = "datepicker", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.Data_Nascimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Numero_Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Numero_Endereco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Numero_Endereco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Municipio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Municipio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" value="Cadastrar" style="background-color: #3872a2" class="btn btn-success pull-right" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-success", @style = "background-color: #3872a2" })
</div>

@section Styles {
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jquery-ui/jqueryuiStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/unobtrusive")
    @Scripts.Render("~/plugins/unobtrusiveMin")
    @Scripts.Render("~/plugins/inspinia")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/plugins/jqueryui")

    <script type="text/javascript">
    function pesquisaCNPJ() {
        $("#carregarCNPJ").click(function () {
            var pesquisa = $("#pesquisaCNPJ").val().toString();
            console.warn(pesquisa);
            $.post('@Url.Action("RetornaDadosPorCNPJ", "CUAUsuarios")', { cnpj : pesquisa })
            .done(function(data){
                console.warn(data);
            });
        });
    };

     //Função para a função de Aprovação/Rejeição
    function showPopUpConfirm(title, text, type) {
        swal({
            title: title,
            text: text,
            type: type,
            showCancelButton: true,
            confirmButtonColor: "#72BF53",
            confirmButtonText: "Aprovar",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {
                    $('.confirm').attr("disabled", "disabled");
                }
                else { swal("Cancelado", "Operação Cancelada", "error"); }
            }
        );
    };
    </script>

}

VitrineVirtual.WEB/Views/CUAUsuarios/Index.cshtml
@model IEnumerable<VitrineVirtual.Model.CUA_Usuarios>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Cadastrar Usuário", "Create", null, new { @class = "btn btn-success", @style = "background-color: #3872a2" })
</p>
<div class="ibox-content m-b-sm border-bottom">
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label class="control-label" for="product_name">Nome Produto</label>
                <input type="text" id="txtNomeEmpresa" name="product_name" class="form-control">
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <label class="control-label" for="quantity">Pesquisar</label>
                <input type="submit" id="btnPesquisar" value="Pesquisar" onclick="chamaPesquisa();" style="background-color: #3872a2" class="btn btn-success " />
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                        <thead>
                            <tr>
                                <th data-toggle="true">Nome Completo</th>
                                <th data-hide="all">Login Usuário</th>
                                <th data-hide="all">Departamento</th>
                                <th data-hide="all">Cargo</th>
                                <th data-hide="all">Status Usuário</th>
                                <th data-hide="all">CNPJ</th>
                                <th class="text-left" data-sort-ignore="true">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nome_Completo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Login_Usuario)
                                </td>
                               
                                <td>
                                    @Html.DisplayFor(modelItem => item.Departamento)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Cargo)
                                </td>
                               
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status_Usuario)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CNPJ)
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn-info btn btn-xs" onclick="location.href='@Url.Action("Details", "CUAUsuarios", new { id = item.ID_Usuario })'"><i class="glyphicon glyphicon-file"></i></button>
                                        <button class="btn-success btn btn-xs" onclick="location.href='@Url.Action("Edit", "CUAUsuarios", new { id = item.ID_Usuario })'"><i class="glyphicon glyphicon-edit"></i></button>
                                        <button class="btn-danger btn btn-xs apaga" value="Assign" onclick="ExcluiProduto(@item.ID_Usuario)"><i class="glyphicon glyphicon-trash"></i></button>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="6">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="@Url.Content("~/Scripts/plugins/slimscroll/jquery.slimscroll.min.js")" type="text/javascript"></script>

@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/codeEditorStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/unobtrusive")
    @Scripts.Render("~/plugins/unobtrusiveMin")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/inspinia")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/slimScroll")

    <script type="text/javascript">

    AddAntiForgeryToken = function (data) {
        data.__RequestVerificationToken = $('#__AjaxAntiForgeryForm input[name=__RequestVerificationToken]').val();
        return data;
    };

    function ExcluiProduto(id) {
        console.warn('Entrou na função, com id:' + id);
        swal({
            title: "Confirma Exclusão?",
            text: "Depois de excluído esse usuário não será recuperado!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Apagar",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {
                     $.post('@Url.Action("Delete", "CUAUsuarios")', AddAntiForgeryToken({ id: id })).done(function(data){
                         console.warn(data);
                     });
                    swal("Usuário Excluído!", "O usuário selecionado foi excluído com sucesso.", "success");
                        window.location.href = '@Url.Action("Index", "CUAUsuarios")';
                } else {
                    swal("Cancelado", "Usuário não pode ser excluído.", "error");
                    window.location.href = '@Url.Action("Index", "CUAUsuarios")';
                }
            });
    }


    </script>

    <script type="text/javascript">
    function chamaPesquisa() {
        $("#btnPesquisar").click(function () {
            var pesquisa = $("#txtNomeUsuario").val().toString();
            console.warn(pesquisa);
            $.post('@Url.Action("FiltrarPorNome", "CUAUsuarios")', AddAntiForgeryToken({ pesquisa: pesquisa }))
            .done(function(data){
                console.warn(data);
            });
        });
    };
    </script>
}
