VitrineVirtual.WEB/Controllers/CUAEmpresasController.cs
using Newtonsoft.Json;
using NLog;
using NLog.Fluent;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using System.Web.UI;
using VitrineVirtual.Data;
using VitrineVirtual.Model;

namespace VitrineVirtual.WEB.Controllers
{
    [AllowAnonymous]
    [Authorize(Roles = "Administrator")]
    public class CUAEmpresasController : Controller
    {
        private VitrineVirtualDBContext db = new VitrineVirtualDBContext();
        Logger log = LogManager.GetCurrentClassLogger();
        Page page = new Page();


        // GET: CUA_Empresas
        public ActionResult Index()
        {
            var listaEmpresas = db.Empresas;
            return View(listaEmpresas);
        }

        /// <summary>
        /// Método de retorno dos dados pela receita federal e correios
        /// </summary>
        /// <param name="cnpj"></param>
        /// <returns></returns>
        public ActionResult RetornaDadosPorCNPJ(string cnpj)
        {
            try
            {
                CUA_Empresas empDados = new CUA_Empresas();
                var resultCNPJ = EmpresaDados(cnpj);

                empDados.Bairro = resultCNPJ.bairro;
                empDados.CEP = resultCNPJ.cep.Replace(".", "").Replace("-", "").Replace("/", "");
                empDados.Cidade = resultCNPJ.municipio;
                empDados.Complemento = resultCNPJ.complemento;
                empDados.Estado = resultCNPJ.uf;
                empDados.Endereco = resultCNPJ.logradouro;
                empDados.Numero = resultCNPJ.numero;
                empDados.Matriz_Filial = resultCNPJ.tipo;
                empDados.Natureza_Juridica = resultCNPJ.natureza_juridica;
                empDados.Nome_Fantasia = resultCNPJ.fantasia;
                empDados.CNPJ = resultCNPJ.cnpj.Replace(".", "").Replace("-", "").Replace("/", "");
                empDados.Razao_Social = resultCNPJ.nome;
                empDados.Situacao_Cadastral = resultCNPJ.situacao;
                empDados.Email = resultCNPJ.email;
                empDados.Telefone = resultCNPJ.telefone.Replace(".", "").Replace("-", "").Replace("/", "");
                empDados.Abertura_Empresa = Convert.ToDateTime(resultCNPJ.abertura);

                if (resultCNPJ.status == "OK")
                    return View("Create", empDados);

                else if(resultCNPJ.status == "ERROR")
                {
                    ViewBag.Error = "CNPJ inválido";
                    return View("Create");
                }
                else
                    return View("Create");
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return null;
            }
        }

        /// <summary>
        /// Método que realiza consulta na API ReceitaWS e retorna os dados da empresa relativa ao CNPJ consultado.
        /// </summary>
        /// <param name="cnpj"></param>
        /// <returns></returns>
        protected ReceitaWS EmpresaDados(string cnpj)
        {
            ReceitaWS jsonResult = new ReceitaWS();
            string responseJson;
            string receitaWS = "https://www.receitaws.com.br/v1/cnpj/";
            string Api_Consulta = receitaWS + cnpj.Replace(".", "").Replace("-", "").Replace("/", "");

            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Clear();
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    using (var request = new HttpRequestMessage(HttpMethod.Get, Api_Consulta))
                    {
                        using (var response = client.SendAsync(request).Result)
                        {
                            if (response.IsSuccessStatusCode)
                            {
                                responseJson = response.Content.ReadAsStringAsync().Result;
                                jsonResult = JsonConvert.DeserializeObject<ReceitaWS>(responseJson);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();

                return null;
            }
            return jsonResult;
        }

        /// <summary>
        /// Método resposável de filtrar por empresas.
        /// </summary>
        /// <param name="pesquisa"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FiltrarPorNome(string pesquisa)
        {
            try
            {
                var produtoSelecionado = db.Empresas.Where(a => a.Nome_Fantasia.Contains(pesquisa)).OrderBy(a => a.Nome_Fantasia).ToList();
                return View(produtoSelecionado);
            }
            catch (Exception ex)
            {
                ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "swalFalhou();", true);
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return RedirectToAction("Index");
            }

        }

        // GET: CUA_Empresas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUA_Empresas Empresas = db.Empresas.Find(id);
            if (Empresas == null)
            {
                return HttpNotFound();
            }
            return View(Empresas);
        }

        // GET: CUA_Empresas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CUA_Empresas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome_Fantasia,Status_Empresa,Data_Criacao,Razao_Social,CEP,Endereco,Numero,Complemento,Bairro,Cidade,Estado,Email,CNPJ,Matriz_Filial,Situacao_Cadastral,Natureza_Juridica,Abertura_Empresa")] CUA_Empresas Empresas)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Empresas.Add(Empresas);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(Empresas);
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return null;
            }

        }

        // GET: CUA_Empresas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUA_Empresas cUA_Empresas = db.Empresas.Find(id);
            if (cUA_Empresas == null)
            {
                return HttpNotFound();
            }
            return View(cUA_Empresas);
        }

        // POST: CUA_Empresas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Empresa,Nome_Empresa,Status_Empresa,Data_Criacao,Data_Alteracao,Nome_Fantasia,Nome_Tecnico,CNPJ")] CUA_Empresas cUA_Empresas)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(cUA_Empresas).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(cUA_Empresas);
            }
            catch (Exception ex)
            {
                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return RedirectToAction("Index");
            }
            
        }

        // GET: CUA_Empresas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUA_Empresas cUA_Empresas = db.Empresas.Find(id);
            if (cUA_Empresas == null)
            {
                return HttpNotFound();
            }
            return View(cUA_Empresas);
        }

        // POST: CUA_Empresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CUA_Empresas cUA_Empresas = db.Empresas.Find(id);
            db.Empresas.Remove(cUA_Empresas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {

VitrineVirtual.WEB/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014 - 2017
    </div>
</div>

VitrineVirtual.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - Vitrine Virtual</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @Html.Partial("_TopNavbar")
        </div>
    </div>
    <div class="container body-content">
        <div class="col-md-3">
            @Html.Partial("_Navigation")
            @*@Html.Partial("_NavigationMenu")*@
        </div>
        <div class="col-md-9">
            @RenderBody()
            <hr />
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - Vitrine Virtual</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    @RenderSection("scripts", required: false)
</body>
</html>

VitrineVirtual.WEB/Views/Shared/_Layout_2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Vitrine Virtual | @ViewBag.Title</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
    <!-- Primary Inspinia style -->
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")

</head>
<body>
    <!-- Skin configuration box -->
    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">
        <!-- Navigation -->
        @Html.Partial("_Navigation")
        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">
            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")
            <!-- Main view  -->
            @RenderBody()
            <!-- Footer -->
            @Html.Partial("_Footer")
        </div>
        <!-- End page wrapper-->
    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

    <script>$('body.canvas-menu .sidebar-collapse').slimScroll({
            height: '100%',
            railOpacity: 0.9
        });</script>
</body>
</html>

VitrineVirtual.WEB/Views/Shared/_Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Login</title>

    <script src='https://www.google.com/recaptcha/api.js'></script>


    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Fonts/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="~/Content/animate.css" rel="stylesheet">
    <link href="~/Content/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <h3>Benvindo ao Vitrine Virtual</h3>
            <p>
                A Vitrine Virtual é um marketplace das melhores lojas do Brás, José Paulino, 25 de março e Franca.
                Vendas exclusivas para pessoas com CNPJ, com muita praticidade, comodidade e rapidez para suas compras.
                Não fique de fora, cadastre-se agora e amplie suas vendas!
            </p>
            <p>Faça o login ou cadastre-se agora e seja um filiado.</p>
            <form class="m-t" role="form" action="#">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Usuário" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Senha" required="">
                </div>
                <div class="g-recaptcha" data-sitekey="6LfRBjcUAAAAAKnoiegXZp_BYc7Dr6d1lKe78YlL"></div>
                <button type="submit" class="btn btn-primary block full-width m-b" style="background-color:#3872a2">Entrar</button>
                <a href="#"><small>Esqueceu a senha?</small></a>
                <p class="text-muted text-center"><small>Logista ou Revendedor, preencha sua proposta de cadastro</small></p>
                <a class="btn btn-sm btn-white btn-block" href="@Url.Action("Register", "Pages")">Enviar Proposta de Cadastro</a>
            </form>
            <p class="m-t"> <small>Faça seu negócio crescer e alcançar o maior número de pessoas. &copy; 2015</small> </p>
        </div>
    </div>

</body>

</html>


@using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()

    <div class="dropdown">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="ma-nav-text ma-account-name">@User.Identity.Name</span>
            <i class="material-icons md-36 text-inverse">person</i>
        </button>

        <ul class="dropdown-menu dropdown-menu-right ma-dropdown-tray">
            <li>
                <a href="javascript:document.getElementById('logoutForm').submit()">
                    <i class="material-icons">system_update_alt</i>
                    <span>Sign out</span>
                </a>
            </li>
        </ul>
    </div>
}

VitrineVirtual.WEB/Views/Shared/_Navigation.cshtml
@using VitrineVirtual.Data;

<form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>


<nav class="navbar-default navbar-static-side" role="navigation" style="background-color: #3872a2">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="~/img/thumbnail_VV.png" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Vitrine Virtual</strong>
                            </span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="@Url.Action("Login", "Pages")">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    VV+
                </div>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Feminina" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Masculina</span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "Home", action: "MenuEmpresas")">
                <a href="@Url.Action("MenuEmpresas", "Home", new { categoria = "Moda_Feminina" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Feminina</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "CadastroProdutoLoja", action: "CatalogoItens", cssClass: "in")">
                    @{
                        VitrineVirtualDBContext db = new VitrineVirtualDBContext();

                        var lstEmpresas = db.Empresas.Select(x => x.Nome_Fantasia).ToList();

                        if (lstEmpresas.Any())
                        {
                            int cont = 0;
                            foreach (var item in lstEmpresas)
                            {

                                @*<li class="@Html.IsSelected(action: "CadastroProdutoLoja")"><a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Feminina", idEmpresa = item.ID_Empresa })"></a>@item.Nome_Fantasia</li>*@
                                <li href="@Html.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Feminina", idEmpresa = @item })">@item</li>
                                cont++;
                            }
                        }

                    }

                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Masculina" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Masculina</span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Praia" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Baby </span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Infanto_Juvenil" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Infato Juvenil</span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Praia" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Praia</span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Fitness" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Fitness</span>
                </a>
            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Moda_Intima" })">
                    <span class="nav-label" style="color:whitesmoke">Moda Intima</span>
                </a>

            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Sapato_Feminino" })">
                    <span class="nav-label" style="color:whitesmoke">Sapatos Femininos</span>
                </a>

            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")" style="color:whitesmoke">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Sapato_Masculino" })">
                    <span class="nav-label" style="color:whitesmoke">Sapatos Masculinos</span>
                </a>

            </li>
            <li class="@Html.IsSelected(controller: "CadastroProdutoLoja")">
                <a href="@Url.Action("CatalogoItens", "CadastroProdutoLoja", new { categoria = "Sapato_Infatil" })">
                    <span class="nav-label" style="color:whitesmoke">Sapato Infatil</span>
                </a>
            </li>
        </ul>
    </div>
    <script src="Scripts/jquery.metisMenu.js"></script>
</nav>

VitrineVirtual.WEB/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <div class="container-fluid" style="background-color: #3872a2">
        <span class="aligncenter">
            <img class="Image of Seal" src="~/img/vvLogo.png" />
        </span>
    </div>

    <nav class="navbar navbar-static-top" role="navigation" style="background-color:#3872a2">
        <ul class="nav navbar-nav" style="background-color:#3872a2">
            <li>@Html.ActionLink("Home", "Index", "Home", null, new { @style = "color:whitesmoke" })</li>
            @if (Request.IsAuthenticated && (User.IsInRole("Administrador") || User.IsInRole("Logista")))
            {
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:whitesmoke">Logista <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Logista", "Tabs", "CadastroProdutoLoja")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Cadastro Produto", "Index", "CadastroProdutoLoja")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Faturamento", "Index", "FaturamentoLoja")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Relatórios", "Index", "RelatorioLoja")</li>
                    </ul>
                </li>
            }

            @if (Request.IsAuthenticated && (User.IsInRole("Administrador") || User.IsInRole("Revendedor")))
            {
                <li>@Html.ActionLink("Revendedor", "Index", "Revendedor", null, new { @style = "color:whitesmoke" })</li>
            }
            <li>@Html.ActionLink("Catálogo", "Index", "CatalogoProdutoLoja", null, new { @style = "color:whitesmoke" })</li>
            <li>@Html.ActionLink("Promocões", "Index", "Promocoes", null, new { @style = "color:whitesmoke" })</li>
            @if (Request.IsAuthenticated && User.IsInRole("Administrador"))
            {
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:whitesmoke">Gestão Portal <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Gerenciamento Usuários", "Index", "Manage")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Cadastro de Usuários", "Index", "CUAUsuarios")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Cadastro de Lojas", "Index", "CUAEmpresas")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Permissões Usuários", "EditUserRoles", "Account")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Faturamento", "Index", "FaturamentoPortal")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Relatórios", "Index", "RelatorioPortal")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Estatisticas PagSeguro", "Index", "EstatisticasPagSeguro")</li>
                    </ul>
                </li>
            }
            
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li style="color:whitesmoke"><b>Olá</b>    @User.Identity.Name</li>
            <li style="vertical-align:">
                <a href="@Url.Action("LogOut", "Account")" style="color:whitesmoke">
                    <i class="fa fa-sign-out" style="color:whitesmoke"></i> Sair
                </a>
            </li>
        </ul>
    </nav>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $(".dropdown-toggle").dropdown();
    });
</script>