VitrineVirtual.WEB/Controllers/CatalogoProdutoLojaController.cs
using NLog.Fluent;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using VitrineVirtual.Data;
using VitrineVirtual.Model;
using PayPal.Api;
using VitrineVirtual.WEB.PayPal;

namespace VitrineVirtual.WEB.Controllers
{
    public class CatalogoProdutoLojaController : Controller
    {
        private VitrineVirtualDBContext db = new VitrineVirtualDBContext();

        //[Authorize(Roles = "Administrator,Logista")]
        public ActionResult Index()
        {
            // TODO: Pegar usuário cliente campo texto login, checar empresa usuário pertence e gravar cookie
            // Também pode usar redis de banco
            var listaProdutos = db.CadastroProdutoLoja.ToList();
            return View(listaProdutos);
        }

        //[Authorize(Roles = "Administrator,Logista")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cadastro_Produto_Loja catalogo_Produto_Loja = db.CadastroProdutoLoja.Find(id);
            if (catalogo_Produto_Loja == null)
            {
                return HttpNotFound();
            }
            return View(catalogo_Produto_Loja);
        }

        //[AllowAnonymous]
        //public ActionResult ModaFeminina(string categoria)
        //{
        //    List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
        //    var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

        //    foreach (var categorias in grupoCategoria)
        //    {
        //        var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
        //        foreach (var produtos in produtosListagem)
        //        {
        //            catalogo_Produto_Loja.Add(produtos);
        //        }
        //    }

        //    return View(catalogo_Produto_Loja);
        //}

        [AllowAnonymous]
        public ActionResult ModaMasculina(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult ModaInfantoJuvenil(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult ModaBaby(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult ModaPraia(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult ModaFitness(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult ModaIntima(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult SapatoFeminino(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult SapatoMasculino(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        [AllowAnonymous]
        public ActionResult SapatoInfatil(string categoria)
        {
            List<Cadastro_Produto_Loja> catalogo_Produto_Loja = new List<Cadastro_Produto_Loja>();
            var grupoCategoria = db.CadastroProdutoLoja.GroupBy(p => p.Categoria_Produto);

            foreach (var categorias in grupoCategoria)
            {
                var produtosListagem = categorias.Where(x => x.Categoria_Produto == categoria);
                foreach (var produtos in produtosListagem)
                {
                    catalogo_Produto_Loja.Add(produtos);
                }
            }

            return View(catalogo_Produto_Loja);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VitrineVirtual.WEB/Controllers/Catalogo_Produto_LojaController.cs
using NLog.Fluent;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using VitrineVirtual.Data;
using VitrineVirtual.Model;

namespace VitrineVirtual.WEB.Controllers
{
    public class Catalogo_Produto_LojaController : Controller
    {
        private VitrineVirtualDBContext db = new VitrineVirtualDBContext();

        // GET: Catalogo_Produto_Loja
        public ActionResult Index()
        {
            // TODO: Pegar usuário cliente campo texto login, checar empresa usuário pertence e gravar cookie
            // Também pode usar redis de banco
            var listaProdutos = db.CadastroProdutoLoja.ToList();
            return View(listaProdutos);
        }

        // GET: Catalogo_Produto_Loja/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cadastro_Produto_Loja catalogo_Produto_Loja = db.CadastroProdutoLoja.Find(id);
            if (catalogo_Produto_Loja == null)
            {
                return HttpNotFound();
            }
            return View(catalogo_Produto_Loja);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VitrineVirtual.WEB/Views/CatalogoProdutoLoja/FailureView.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sample</title>
</head>
<body>
    <div>
        Payment Failed! 
    </div>
</body>
</html>

VitrineVirtual.WEB/Views/CatalogoProdutoLoja/Index.cshtml
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" />
<h2>Catalogo Produtos</h2>


<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation">
                                    <span class="product-images">
                                        @Html.DisplayFor(modelItem => item.Foto_Produto_1)
                                    </span>
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("Details", "CatalogoProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

VitrineVirtual.WEB/Views/CatalogoProdutoLoja/ModaFitness.cshtml

@{
    ViewBag.Title = "Moda Fitness";
}

<h2>Moda Fitness</h2>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" />

<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation">
                                    <span class="product-images">
                                        @Html.DisplayFor(modelItem => item.Foto_Produto_1)
                                    </span>
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("ModaMasculina", "CatalogoProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


VitrineVirtual.WEB/Views/CatalogoProdutoLoja/ModaInfantoJuvenil.cshtml
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "Moda Infanto Juvenil";
}

<h2>Moda Infanto Juvenil</h2>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" />

<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation">
                                    <span class="product-images">
                                        @Html.DisplayFor(modelItem => item.Foto_Produto_1)
                                    </span>
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("ModaMasculina", "CatalogoProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


VitrineVirtual.WEB/Views/CatalogoProdutoLoja/ModaIntima.cshtml
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "ModaIntima";
}

<h2>ModaIntima</h2>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" />

<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation">
                                    <span class="product-images">
                                        @Html.DisplayFor(modelItem => item.Foto_Produto_1)
                                    </span>
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("ModaMasculina", "CatalogoProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


VitrineVirtual.WEB/Views/CatalogoProdutoLoja/ModaMasculina.cshtml
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>


@{
    ViewBag.Title = "Moda Masculina";
}


<h2>Moda Masculina</h2>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" />

<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation">
                                    <span class="product-images">
                                        @Html.DisplayFor(modelItem => item.Foto_Produto_1)
                                    </span>
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("Details", "CatalogoProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

VitrineVirtual.WEB/Views/CatalogoProdutoLoja/ModaPraia.cshtml
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "Moda Praia";
}

<h2>Moda Praia</h2>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css" />

<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation">
                                    <span class="product-images">
                                        @Html.DisplayFor(modelItem => item.Foto_Produto_1)
                                    </span>
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("ModaMasculina", "CatalogoProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

VitrineVirtual.WEB/Views/CatalogoProdutoLoja/PaymentWithPaypal.cshtml

@{
    ViewBag.Title = "PaymentWithPaypal";
}

<h2>PaymentWithPaypal</h2>


VitrineVirtual.WEB/Views/CatalogoProdutoLoja/SuccessView.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sample</title>
</head>
<body>
    <div> 
        Payment Successful
    </div>
</body>
</html>