VitrineVirtual.WEB/Controllers/CadastroProdutoLojaController.cs
using NLog;
using NLog.Fluent;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using VitrineVirtual.Data;
using VitrineVirtual.Model;


namespace VitrineVirtual.WEB.Controllers
{
    //[Authorize(Roles = "Administrator,Logista")]
    public class CadastroProdutoLojaController : Controller
    {
        private VitrineVirtualDBContext db = new VitrineVirtualDBContext();
        Logger log = LogManager.GetCurrentClassLogger();
        Page page = new Page();

        public ActionResult Index()
        {
            // TODO: Pegar usuário cliente campo texto login, checar empresa usuário pertence e gravar cookie
            // Também pode usar redis de banco
            var listaProdutos = db.CadastroProdutoLoja;
            //ViewBag.Empresas = new SelectList(db.Empresas.ToList(), "ID_Empresa", "Nome_Fantasia");
            return View(listaProdutos);
        }

        /// <summary>
        /// Método resposável de filtrar por produto.
        /// </summary>
        /// <param name="pesquisa"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FiltrarPorNome(string pesquisa)
        {
            try
            {
                var produtoSelecionado = db.CadastroProdutoLoja.Where(a => a.Nome_Produto.Contains(pesquisa)).OrderBy(a => a.Nome_Produto).ToList();
                return View(produtoSelecionado);
            }
            catch (Exception ex)
            {

                ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "swalFalhou();", true);
                Log.Info(ex.Message);
                return RedirectToAction("Index");
            }

        }

        // GET: CADASTRO_PRODUTO_LOJA/Details/5
        public ActionResult Details(int? id)
        {
            Cadastro_Produto_Loja cadastroProdutoLoja;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                cadastroProdutoLoja = db.CadastroProdutoLoja.Find(id);

                this.page.Session.Add("ID_Cadastro_Prod_Loja", cadastroProdutoLoja.ID_Cadastro_Prod_Loja);
                this.page.Session.Add("Nome_Produto", cadastroProdutoLoja.Nome_Produto);
                this.page.Session.Add("Preco_Produto", cadastroProdutoLoja.Preco_Produto);
                this.page.Session.Add("Preco_Desconto", cadastroProdutoLoja.Preco_Desconto);
                this.page.Session.Add("Quantidade_Produto", cadastroProdutoLoja.Quantidade_Produto);
                this.page.Session.Add("Modelo_Produto", cadastroProdutoLoja.Modelo_Produto);

                this.page.Session.Add("Item_Compra", cadastroProdutoLoja);


                var usuario = Session["ID_Usuario"].ToString();

                var dadosUsuario = db.Usuarios.Where(x => x.id == usuario).ToList();
                //var dadosUsuario = db.Usuarios.SingleOrDefault(x => x.id == usuario);

                if (dadosUsuario.Count != 0)
                {
                    this.page.Session.Add("Nome_Completo", dadosUsuario[0].Nome_Completo);
                    this.page.Session.Add("Endereco", dadosUsuario[0].Endereco);
                    this.page.Session.Add("Numero_Endereco", dadosUsuario[0].Numero_Endereco);
                    this.page.Session.Add("Municipio", dadosUsuario[0].Municipio);
                    this.page.Session.Add("Cep", dadosUsuario[0].Cep);
                    this.page.Session.Add("Telefone", dadosUsuario[0].Telefone);
                    this.page.Session.Add("UF", dadosUsuario[0].UF);

                }

            }
            catch (Exception ex)
            {

                log.Log(LogLevel.Error)
                  .Exception(ex)
                  .Message("Mensagem de log {0} parametro", 1).Write();
                return View();
            }

            if (cadastroProdutoLoja == null)
            {
                return HttpNotFound();
            }
            return View(cadastroProdutoLoja);

        }

        // GET: CADASTRO_PRODUTO_LOJA/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: CADASTRO_PRODUTO_LOJA/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Cadastro_Prod_Loja,Nome_Produto,Modelo_Produto,Descricao_Produto,Preco_Produto,Quantidade_Produto,Status_Produto,Categoria_Produto")]Cadastro_Produto_Loja cadastro_Produto_Loja, HttpPostedFileBase upload1, HttpPostedFileBase upload2, HttpPostedFileBase upload3, HttpPostedFileBase upload4)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (upload1 != null && upload1.ContentLength > 0)
                    {
                        var foto = new FilePath
                        {
                            Nome_Arquivo = Guid.NewGuid().ToString() + Path.GetExtension(upload1.FileName),
                            Tipo_Arquivo = Path.GetExtension(upload1.FileName)
                        };
                        foto.Caminho_Arquivo = Path.Combine(Server.MapPath("~/images/uploads"), foto.Nome_Arquivo);
                        upload1.SaveAs(foto.Caminho_Arquivo);
                        cadastro_Produto_Loja.FilePath = new List<FilePath>();
                        cadastro_Produto_Loja.FilePath.Add(foto);
                    }

                    if (upload2 != null && upload2.ContentLength > 0)
                    {
                        var foto = new FilePath
                        {
                            Nome_Arquivo_2 = Guid.NewGuid().ToString() + Path.GetExtension(upload2.FileName),
                            Tipo_Arquivo = Path.GetExtension(upload2.FileName)
                        };
                        foto.Caminho_Arquivo = Path.Combine(Server.MapPath("~/images/uploads"), foto.Nome_Arquivo_2);
                        upload2.SaveAs(foto.Caminho_Arquivo);
                        cadastro_Produto_Loja.FilePath = new List<FilePath>();
                        cadastro_Produto_Loja.FilePath.Add(foto);
                    }

                    if (upload3 != null && upload3.ContentLength > 0)
                    {
                        var foto = new FilePath
                        {
                            Nome_Arquivo_3 = Guid.NewGuid().ToString() + Path.GetExtension(upload3.FileName),
                            Tipo_Arquivo = Path.GetExtension(upload3.FileName)
                        };
                        foto.Caminho_Arquivo_3 = Path.Combine(Server.MapPath("~/images/uploads"), foto.Nome_Arquivo_3);
                        upload3.SaveAs(foto.Caminho_Arquivo_3);
                        cadastro_Produto_Loja.FilePath = new List<FilePath>();
                        cadastro_Produto_Loja.FilePath.Add(foto);
                    }

                    if (upload4 != null && upload4.ContentLength > 0)
                    {
                        var foto = new FilePath
                        {
                            Nome_Arquivo_4 = Guid.NewGuid().ToString() + Path.GetExtension(upload4.FileName),
                            Tipo_Arquivo = Path.GetExtension(upload4.FileName)
                        };
                        foto.Caminho_Arquivo_4 = Path.Combine(Server.MapPath("~/images/uploads"), foto.Nome_Arquivo_4);
                        upload4.SaveAs(foto.Caminho_Arquivo_4);
                        cadastro_Produto_Loja.FilePath = new List<FilePath>();
                        cadastro_Produto_Loja.FilePath.Add(foto);
                    }


                    db.CadastroProdutoLoja.Add(cadastro_Produto_Loja);
                    db.SaveChanges();

                    var path = Path.Combine(Server.MapPath("~/images/temp"));
                    FileInfo file = new FileInfo(path);
                    if (file.Exists)
                        file.Delete();

                    ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "swalSucesso();", true);
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "swalFalhou();", true);
                    log.Log(LogLevel.Error)
                      .Exception(ex)
                      .Message("Mensagem de log {0} parametro", 1).Write();
                    return RedirectToAction("Index");
                }
            }

            return View(cadastro_Produto_Loja);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cadastro_Produto_Loja cadastro_Produto_Loja = db.CadastroProdutoLoja.Find(id);
            if (cadastro_Produto_Loja == null)
            {
                return HttpNotFound();
            }
            return View(cadastro_Produto_Loja);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(int? id, HttpPostedFileBase upload1, HttpPostedFileBase upload2, HttpPostedFileBase upload3, HttpPostedFileBase upload4)
        {
            if (id == null)
            {

VitrineVirtual.WEB/Views/CadastroProdutoLoja/CatalogoItens.cshtml
@using VitrineVirtual.Model
@using VitrineVirtual.WEB.Controllers
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "Catalogo de Produtos";
}

<h2>Moda Feminina</h2>


<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation" style="background-size: 250px 210px">
                                    @{
                                        ((CadastroProdutoLojaController)this.ViewContext.Controller).GetImage(item.ID_Cadastro_Prod_Loja);
                                        var cadProd = (Cadastro_Produto_Loja)Session["Foto"];

                                        if (Session["caminho_1"] != null)
                                        {
                                            var caminhoFoto1 = (FilePath)Session["caminho_1"];

                                            <a href="#" title="Foto 1">
                                                <img style="position:initial" width="240" height="200" src="@Url.Content(caminhoFoto1.Caminho_Arquivo)" />
                                            </a>
                                        }
                                    }
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Desconto)
                                    </span>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("Details", "CadastroProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/codeEditorStyles")
    @Styles.Render("~/plugins/jquery-ui/jqueryuiStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/unobtrusive")
    @Scripts.Render("~/plugins/unobtrusiveMin")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/inspinia")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/plugins/jqueryui")

    <script type="text/javascript">

        AddAntiForgeryToken = function (data) {
            data.__RequestVerificationToken = $('#__AjaxAntiForgeryForm input[name=__RequestVerificationToken]').val();
            return data;
        };

        function SucessoPagamento(id) {
            swal({
                title: "Pagamento Efetuado",
                text: "Seu pagamento foi realizado com sucesso!",
                type: "success",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Confirmar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        swal("Pagamento Efetuado!", "Seu pagamento foi realizado com sucesso.", "success");
                    };
                });
        }

        function FalhaPagamento(id) {
            swal({
                title: "Pagamento Não Efetuado",
                text: "Seu pagamento falhou, tente novamente ou entre em contato com a administradora do seu cartão ou em seus dados no PayPal!",
                type: "error",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Confirmar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        swal("Pagamento Não Efetuado!", "Seu pagamento falhou, tente novamente ou entre em contato com a administradora do seu cartão ou em seus dados no PayPal!", "error");
                    };
                });
        }

    </script>
}


VitrineVirtual.WEB/Views/CadastroProdutoLoja/Delete.cshtml
@model VitrineVirtual.Model.Cadastro_Produto_Loja

@{
    ViewBag.Title = "Delete";
}

<h2>Apaga Item</h2>

<h4>Tem certeza que deseja apagar esse produto da lista?</h4>
<h4>Depois de apagado da sua lista esses produtos não serão mais vistos ou editados</h4>
<div>
    <h3>Apaga Produto</h3>
    <hr />
    <dl class="dl-horizontal">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ID_Cadastro_Prod_Loja)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome_Produto)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categoria_Produto)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descricao_Produto)
            </dd>
        </dl>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Voltar", "Index")

    </div>
    }
</div>

VitrineVirtual.WEB/Views/CadastroProdutoLoja/Index.cshtml
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/3.0.4/metisMenu.css" />

<h2>Lista Produtos</h2>

<form id="__AjaxAntiForgeryForm" action="#" method="post"> @Html.AntiForgeryToken()</form>

<p>
    @Html.ActionLink("Cadastrar Produto", "Create", null, new { @class = "btn btn-success", @style = "background-color: #3872a2" })

</p>

<div class="ibox-content m-b-sm border-bottom">
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label class="control-label" for="product_name">Nome Produto</label>
                <input type="text" id="txtNomeProduto" name="product_name" class="form-control">
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <label class="control-label" for="quantity">Pesquisar</label>
                <input type="submit" id="btnPesquisar" value="Pesquisar" onclick="chamaPesquisa();" style="background-color: #3872a2" class="btn btn-success " />
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                        <thead>
                            <tr>
                                <th data-toggle="true">Nome Produto</th>
                                <th data-hide="all">Modelo</th>
                                <th data-hide="all">Categoria</th>
                                <th data-hide="all">Preço</th>
                                <th data-hide="all">Quantidade</th>
                                <th data-hide="all">Status</th>
                                <th class="text-left" data-sort-ignore="true">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Categoria_Produto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <button class="btn-info btn btn-xs" onclick="location.href='@Url.Action("Details", "CadastroProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })'"><i class="glyphicon glyphicon-file"></i></button>
                                            <button class="btn-success btn btn-xs" onclick="location.href='@Url.Action("Edit", "CadastroProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })'"><i class="glyphicon glyphicon-edit"></i></button>
                                            <button class="btn-danger btn btn-xs apaga" value="Assign" onclick="ExcluiProduto(@item.ID_Cadastro_Prod_Loja)"><i class="glyphicon glyphicon-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="6">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/codeEditorStyles")
    @Styles.Render("~/plugins/jquery-ui/jqueryuiStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/unobtrusive")
    @Scripts.Render("~/plugins/unobtrusiveMin")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/inspinia")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/plugins/jqueryui")

    <script type="text/javascript">

    AddAntiForgeryToken = function (data) {
        data.__RequestVerificationToken = $('#__AjaxAntiForgeryForm input[name=__RequestVerificationToken]').val();
        return data;
    };

    function ExcluiProduto(id) {
        console.warn('Entrou na função, com id:' + id);
        swal({
            title: "Confirma Exclusão?",
            text: "Depois de excluído esse produto não será recuperado!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Apagar",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {
                     $.post('@Url.Action("Delete", "CadastroProdutoLoja")', AddAntiForgeryToken({ id: id })).done(function(data){
                         console.warn(data);
                     });
                    swal("Produto Excluído!", "O produto selecionado foi excluído com sucesso.", "success");
                    window.location.href = '@Url.Action("Index", "CadastroProdutoLoja")';
                } else {
                    swal("Cancelado", "Produto não pode ser excluído.", "error");
                    window.location.href = '@Url.Action("Index", "CadastroProdutoLoja")';
                }
            });
    }


    </script>

    <script type="text/javascript">
        $("#btnPesquisar").click(function () {
            var pesquisa = $("#txtNomeProduto").val().toString();
            console.warn(pesquisa);
            $.post('@Url.Action("FiltrarPorNome", "CadastroProdutoLoja")', AddAntiForgeryToken({ pesquisa: pesquisa }))
            .done(function(data){
                console.warn(data);
            });
        });
    </script>
}



VitrineVirtual.WEB/Views/CadastroProdutoLoja/ModaFeminina.cshtml
@using VitrineVirtual.Model
@using VitrineVirtual.WEB.Controllers
@model IEnumerable<VitrineVirtual.Model.Cadastro_Produto_Loja>

@{
    ViewBag.Title = "Catalogo de Produtos";
}

<h2>Moda Feminina</h2>


<div class="row wrapper wrapper-content border-bottom white-bg">
    <div class="animated fadeInRight">
        <div class="col-sm-12">
            <div class="form-group">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 form-group">
                        <div class="ibox-block">
                            <div class="ibox-block-content product-box">
                                <div class="product-imitation" style="background-size: 250px 210px">
                                    @{
                                        ((CadastroProdutoLojaController)this.ViewContext.Controller).GetImage(item.ID_Cadastro_Prod_Loja);
                                        var cadProd = (Cadastro_Produto_Loja)Session["Foto"];

                                        if (Session["caminho_1"] != null)
                                        {
                                            var caminhoFoto1 = (FilePath)Session["caminho_1"];

                                            <a href="#" title="Foto 1">
                                                <img style="position:initial" width="240" height="200" src="@Url.Content(caminhoFoto1.Caminho_Arquivo)" />
                                            </a>
                                        }
                                    }
                                </div>
                                <div class="product-desc">
                                    <span class="product-price" style="background-color: #3872a2">
                                        @Html.DisplayFor(modelItem => item.Preco_Produto)
                                    </span>
                                    <small class="product-name">
                                        @Html.DisplayFor(modelItem => item.Nome_Produto)
                                    </small>
                                    <a class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Modelo_Produto)
                                    </a>
                                    <small class="text-muted">
                                        @Html.DisplayFor(modelItem => item.Descricao_Produto)
                                    </small>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Quantidade_Produto)
                                    </div>
                                    <div class="small m-t-xs">
                                        @Html.DisplayFor(modelItem => item.Status_Produto)
                                    </div>
                                    <div class="m-t text-righ">
                                        <a class="btn btn-xs btn-outline btn-info" href="@Url.Action("Details", "CadastroProdutoLoja", new { id = item.ID_Cadastro_Prod_Loja })">Info<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/codeEditorStyles")
    @Styles.Render("~/plugins/jquery-ui/jqueryuiStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/unobtrusive")
    @Scripts.Render("~/plugins/unobtrusiveMin")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/inspinia")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/plugins/jqueryui")

    <script type="text/javascript">

        AddAntiForgeryToken = function (data) {
            data.__RequestVerificationToken = $('#__AjaxAntiForgeryForm input[name=__RequestVerificationToken]').val();
            return data;
        };

        function SucessoPagamento(id) {
            swal({
                title: "Pagamento Efetuado",
                text: "Seu pagamento foi realizado com sucesso!",
                type: "success",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Confirmar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        swal("Pagamento Efetuado!", "Seu pagamento foi realizado com sucesso.", "success");
                    };
                });
        }

        function FalhaPagamento(id) {
            swal({
                title: "Pagamento Não Efetuado",
                text: "Seu pagamento falhou, tente novamente ou entre em contato com a administradora do seu cartão ou em seus dados no PayPal!",
                type: "error",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Confirmar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        swal("Pagamento Não Efetuado!", "Seu pagamento falhou, tente novamente ou entre em contato com a administradora do seu cartão ou em seus dados no PayPal!", "error");
                    };
                });
        }

    </script>
}
